SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'student' -- 🚨 替换为你要查询的数据库名
ORDER BY TABLE_NAME, ORDINAL_POSITION;